version: '3'

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_maxSize=1G

  master:
    image: bde2020/spark-master:2.2.1-hadoop2.7
    container_name: master
    ports:
      - "9080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==master"
  worker-1:
    image: bde2020/spark-worker:2.2.1-hadoop2.7
    container_name: worker-1
    depends_on:
      - master
    ports:
      - "9081:8081"
    environment:
      - "SPARK_MASTER=spark://master:7077"
      - "constraint:node==master"
    volumes:
      - ../data:/data
  worker-2:
    image: bde2020/spark-worker:2.2.1-hadoop2.7
    container_name: worker-2
    depends_on:
      - master
    ports:
      - "9082:8081"
    environment:
      - "SPARK_MASTER=spark://master:7077"
      - "constraint:node==master"
    volumes:
      - ../data:/data

  submit:
    image: default/meetup_demo
    depends_on:
      - master
      - neo4j
    ports:
      - "4040:4040"
    environment:
      - "NEO4J_URL=bolt://neo4j"
      - "ENABLE_INIT_DAEMON=false"
      - "SPARK_MASTER=spark://master:7077"
      - "SPARK_APPLICATION_JAR_NAME=meetup_demo-assembly-0.1.jar"
      - "SPARK_APPLICATION_MAIN_CLASS=demo.DemoJob"
      - "SPARK_MASTER_NAME=master"
      - "constraint:node==master"
    volumes:
      - ../data:/data